### ISSUE TITLE
Notification contents order change

### ISSUE THREAD

**Issue by Kamul-PL** [fi3te/NotificationCron#18]
Currently notifications looks like that:
*20:00:00 Test notification*
which is problematic in case of my smartwatch, where only:
*20:00:00...*
is displayed in notifications preview. Because the notification content is much more important than notification time (which is quite obvious), changing the display order to something like that:
*Test notification - 20:00:00*
will solve the problem. Could you consider making such a simple change?

**Comment by hXtreme** [comment]
I took think that the time is kind of intrusive while also being a bit redundant as android notifications already come with a time indicator (even though it isn't precise and just displays the time elapsed since the notification).

So either the time can be moved behind as suggested in the issue or alternatively just removed from the notification.

**Comment by fi3te** [comment]
Hi Kamul-PL,

please excuse my late reply!

Yes, the order should be changed and the time might even be optional.

Best regards,
Fiete

**Comment by hXtreme** [comment]
Can you assign this to me?

**Comment by fi3te** [comment]
In the next release the time display is optional 😄
